# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: |
    echo '*** SDKs do .NET intalados ***'
    dotnet --list-sdks
- task: UseDotNet@2
  inputs:
   packageType: 'sdk'
   version: '6.0.402'

   
- script: |
    echo '*** Versão assumida como default para o .NET ***'
    dotnet --version
    echo '*** Instalar EF Core Tools ***'
    dotnet tool install --global dotnet-ef
    dotnet ef


- script: |
    cd src/FIAPPOSTECH_FASE2.Infra
    dotnet ef migrations add IntegrationTests
    dotnet ef --startup-project ../FIAPPOSTECH_FASE2.API database update 



- script: |
    cd src/FIAPPOSTECH-FASE2.API.Tests
    dotnet add package TestContainers.Container.Database.MySql --version 3.5.0


- script: |
    cd scr/FIAPPOSTECH-FASE2.API.Tests
    dotnet test --logger "console;verbosity=detailed"

